Repository ArmanKumar21/python-cpp-html-programs-projects, pull requests merged in 2022-10, with the labels that each got.

#3 tic tac game
  Python/tictac.py
Labels: good first issue, hactoberfest-accepted, hactoberfest

#7 Added 21 number game
  Python/21number.py
  Python/rockpaperscissorgame.py
Labels: good first issue, hactoberfest-accepted, hactoberfest

#8 Added 2048 game
  Python/2048game.py
  Python/pokemon.py
Labels: good first issue, hactoberfest-accepted, hactoberfest

#9 Added keylogger
  Python/keylogger.py
Labels: good first issue, hactoberfest-accepted, hactoberfest

#10 Calculator
  Python/Simple_calculator.py
Labels: good first issue, hactoberfest-accepted, hactoberfest

#14 Added age calculator
  Python/C.I_calculator.py
  Python/age_calculator.py
Labels: hacktoberfest, hacktoberfest-accepted

#15 Added weight calculator
  Python/weightcalc.py
Labels: hacktoberfest-accepted

#16 Check if array are equal or not
  Cpp/Check_if_arrays_are_equal_or_not.cpp
Labels: hacktoberfest-accepted

#19 Create Turtle.py
  Python/Turtle.py
Labels: hacktoberfest-accepted

#17 Added sort012.cpp
  Cpp/sort012.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#20 Add two Binary numbers in cpp
  Cpp/Add two Binary numbers.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#22 Solution of Merge Two Sorted Lists #4
  Cpp/MergeTwoSortedList.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#24 Added Countdown timer
  Python/countdowntimer.py
Labels: hacktoberfest, hacktoberfest-accepted

#25 digitalClock in python
  Python/digitalclock.py
Labels: hacktoberfest, hacktoberfest-accepted

#26 Added majority
  majority.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#27 Minesweeper game by Aman
  Cpp/minesweeper_game.cpp
  Cpp/minesweeper_game.exe
Labels: hacktoberfest, hacktoberfest-accepted

#28 Bookshop management by Aman
  Cpp/bookshop_management_system.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#33 printing matrix in spiral form
  printing_matrix_in_spiral.py
Labels: hacktoberfest, hacktoberfest-accepted

#39 added MaxXor.cpp file which can help finding the maximum xor in an array
  C++/MaxXor.cpp
Labels: hacktoberfest, hacktoberfest-accepted, done

#41 Create PhoneBook
  C++/PhoneBook
Labels: hacktoberfest, hacktoberfest-accepted

#42 Added code for merging intervals issue#36
  C++/mergeInterval.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#48 Create Remove one element.cpp
  C++/Remove one element.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#32 Added solution for Minimize the heights II(Python)
  Python/Minimize_the_heights_II.py
Labels: hacktoberfest, hacktoberfest-accepted, done

#55 heap.cpp
  C++/heap.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#57 Reverse Nodes in K groups
  C++/Reverse_nodes_in_k_groups.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#60 Added Median of two sorted arrays C++ code
  C++/Median_of_two_sorted_arrays.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#64 Create Print the Fibonacci sequence
  Python/Print the Fibonacci sequence
Labels: hacktoberfest, hacktoberfest-accepted

#66 Added sudoku solver - C++
  C++/Sudoku_solver.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#72 Merge Two BST added
  Cpp/MergeTwoBst.cpp
  Python/MergeTwoBst.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#71 Kadane's Algorithm in C++
  C++/Kadane.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#73 Mergesort
  Cpp/Implementation of meerge sort/mergesort.cpp
  Cpp/Implementation of meerge sort/readme.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#74 Egg Catcher game in python was added
  Python/eggCatcher.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#75 Added KMP_algorithm.cpp
  C++/KMP_algorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#76 Added Minimize Height cpp and exe file
  Cpp/MinimizeHeight2.cpp
  Cpp/MinimizeHeight2.exe
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#83 Added C++ code for Floyd’s Cycle Finding Algorithm to find the start
  .DS_Store
  C++/Floyd’s Cycle Detection Algorithm to find the start of the loop.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#85 Create Tower of Hanoi.py
  Python/Tower of Hanoi.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#80 Convert any pdf file into audio book. Added AudioBook.py
  Python/AudioBook.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#82 Added Rotting Oranges
  C++/Rotting Oranges.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#63 I have made merge sort using cpp.
  C++/mergesort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#81 Create Palindrome Free Strings.cpp
  C++/Palindrome Free Strings.cpp
  Cpp/String Game.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#79 Create price_email.py
  Python/price_email.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#88 Bucket_sort_added
  C++/Bucket_sort
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#87 Tower of Hanoi in python #84
  Python/Tower of Hanoi/Tower of Hanoi.md
  Python/Tower of Hanoi/towerofhanoi.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#86 Quick_sort_added
  C++/Quick_Sort_Added
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#90 cycle detection in linked list added
  Cpp/CycleDetection_InLinkedList.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#77 Added 3Sum - Leetcode
  C++/3Sum.cpp
  C++/Rotate_Image.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#96 Report Card Making System
  Cpp/Report Card making System .CPP
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#99 Create quizGame.py
  Python/quizGame.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#98 Tower of Hanoi
  Tower of Hanoi
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#97 Create countSort.cpp
  Cpp/countSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#92 Added Merge K Sorted List - Python
  Python/Merge_K_Sorted_List.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#94 Create BFS and DFS traversal of a graph using adjacency list.cpp
  3Sum.cpp
  C++/BFS and DFS traversal of a graph using adjacency list.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#93 Added Quicksort Algo
  Cpp/Quicksort/README.md
  Cpp/Quicksort/quicksort.cpp
  Cpp/Quicksort/quicksort.exe
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#104 Solution for Charecter Rangoli
  Python/character_rangoli.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#112 Alphabets rangoli using python
  Python/rangoli.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#95 Implementation of quick sort
  Python/Implementation of quick sort
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#115 Searching algorithms in cpp
  Cpp/Search/Binary Search.cpp
  Cpp/Search/Linear Search.cpp
  Cpp/Search/searching.cpp
  Cpp/Search/ternary_search.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#113 Regular Expression Matching Problem in C++ #107
  Cpp/regular expression matching.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#114 Create BotClean Stochastic
  C++/BotClean Stochastic
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#118 Merge nodes in between zeros
  C++/Merge Nodes in Between Zeros
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#120 Create snek.py
  Python/snek.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#119 Added Array as Abstract Data Type Program
  Cpp/Array_As_ADT.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#122 Create minimum number of jumps cpp
  minimum_number_of_jumps.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#121 spiral_matrix
  C++/spiral_matrix
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#125 Health Management System added
  Python/Health_Management_System.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#126 Added Leap Year
  Faulty_Calculator.py
  Leap_Year.py
  Password_Check.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#127 Create Longest valid Parentheses.cpp
  Cpp/Longest valid Parentheses.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#124 Create fractalDraw.py
  fractalDraw.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#132 Added Faulty Calculator
  Python/Faulty_Calculator.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#134 Hey this is my first html game. kindly merge it.
  HtmlGame/CarGame.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#129 Made insertion sort
  Python/insertion_sort.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#136 This is my first game in python kindly merge it .
  Python/CatchTheBall.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#137 pet in python. kindly merge it.
  Python/pet.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#138 Added Lexicographically smallest string.cpp updated
  Cpp/Lexicographically smallest string.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#130 Create analogClock.py
  Python/analogClock.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#140 Create Reversing_the_equation.py
  Python/Reversing_the_equation.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#143 I have added a voice based calculator built on VanillaJS inside another folder namely Javascript projects.
  Javascript projects/Voice operated calculator/B.jpg
  Javascript projects/Voice operated calculator/Instructions.css
  Javascript projects/Voice operated calculator/Instructions.html
  Javascript projects/Voice operated calculator/M1.jpg
  Javascript projects/Voice operated calculator/S (1).html
  Javascript projects/Voice operated calculator/S.css
  Javascript projects/Voice operated calculator/S.js
  Javascript projects/Voice operated calculator/back.jpg
  Javascript projects/Voice operated calculator/debug.log
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#145 Added C++ codes for nqueens and topological sort
  C++/nqueens.cpp
  C++/topologicalsort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#150 Added Aaron's Quest IV game
  Aaron’s Quest IV While Moses Was Away/Build/.editorconfig
  Aaron’s Quest IV While Moses Was Away/Build/.gitignore
  Aaron’s Quest IV While Moses Was Away/Build/Checks.js
  Aaron’s Quest IV While Moses Was Away/Build/Compress.js
  Aaron’s Quest IV While Moses Was Away/Build/Config.js
  Aaron’s Quest IV While Moses Was Away/Build/README.md
  Aaron’s Quest IV While Moses Was Away/Build/appbundle.js
  Aaron’s Quest IV While Moses Was Away/Build/config_project.js
  Aaron’s Quest IV While Moses Was Away/Build/eslint.js
  Aaron’s Quest IV While Moses Was Away/Build/exec.js
  Aaron’s Quest IV While Moses Was Away/Build/gulpish.js
  Aaron’s Quest IV While Moses Was Away/Build/gulpish_bundle.js
  Aaron’s Quest IV While Moses Was Away/Build/gulpish_tasks.js
  Aaron’s Quest IV While Moses Was Away/Build/imgproc.js
  Aaron’s Quest IV While Moses Was Away/Build/index.js
  Aaron’s Quest IV While Moses Was Away/Build/jsjam22.sublime-project
  Aaron’s Quest IV While Moses Was Away/Build/json5.js
  Aaron’s Quest IV While Moses Was Away/Build/package-lock.json
  Aaron’s Quest IV While Moses Was Away/Build/package.json
  Aaron’s Quest IV While Moses Was Away/Build/resize.js
  Aaron’s Quest IV While Moses Was Away/Build/spritesheet.js
  Aaron’s Quest IV While Moses Was Away/Build/ss1.png
  Aaron’s Quest IV While Moses Was Away/Build/ss2.png
  Aaron’s Quest IV While Moses Was Away/Build/typescript.js
  Aaron’s Quest IV While Moses Was Away/Build/uglify.js
  Aaron’s Quest IV While Moses Was Away/Build/warnmatch.js
  Aaron’s Quest IV While Moses Was Away/Build/web_fsbuild.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#151 Added ATM Simulator
  C++/Atm _Simulator/.gitignore
  C++/Atm _Simulator/Makefile
  C++/Atm _Simulator/README.md
  C++/Atm _Simulator/atm.cpp
  C++/Atm _Simulator/atm.exe
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#146 Added Shortest Distance in a Binary Maze.cpp
  Cpp/Shortest Distance in a Binary Maze.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#154 Print Floyd's Triangle
  C++/floyds.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#153 cashflow_minimizer
  C++/cashflow_minimizer.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#157 added josephus problem
  C++/Josephus.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
